import crypto from "node:crypto"; import {Lead} from "../models/Lead"; import {LeadSource} from "../models/LeadSource";
export const STATUS_SUGGESTIONS=["New","Called — no answer","Interested","Site visit planned","Follow-up","Quotation sent","Not interested","Converted"];
const clean=(v:unknown,max=4000)=>typeof v==="string"?v.trim().slice(0,max):"";
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===","&&!quoted){row.push(cell);cell="";}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&text[i+1]==="\n")i++;row.push(cell);rows.push(row);row=[];cell="";}else cell+=c;}if(cell.length||row.length){row.push(cell);rows.push(row)}return rows}
function normalizePhone(raw:string){const digits=raw.replace(/\D/g,"");const ten=digits.length===12&&digits.startsWith("91")?digits.slice(2):digits;if(ten.length!==10||!/^[6-9]\d{9}$/.test(ten)||ten==="9999999999")return null;return `+91${ten}`}
function sheetRef(url:string){const m=url.match(/spreadsheets\/d\/([a-zA-Z0-9_-]+)/);if(!m)return null;const gid=(url.match(/[#?&]gid=(\d+)/)||[])[1]||"0";return{sheetId:m[1],gid}}
function inferCategory(hint:string){const s=hint.toLowerCase();if(/construction|construct/.test(s))return"Construction";if(/interior/.test(s))return"Interior";if(/sale|purchase|buy|sell/.test(s))return"Sale / Purchase";return""}
export async function accessibleSources(userId:string){return LeadSource.find({$or:[{ownerId:userId},{sharedWith:userId}]})}
export async function leadAccessFilter(userId:string){const ids=(await accessibleSources(userId)).map(s=>s._id);return{$or:[{ownerId:userId},{sourceIds:{$in:ids}}]}}
const hash=(text:string)=>crypto.createHash("sha256").update(text).digest("hex"); export const parseLeadSourceUrl=(url:string)=>sheetRef(url);
export async function syncSource(source:any,ownerId:string,force=false){const csvUrl=`https://docs.google.com/spreadsheets/d/${source.sheetId}/export?format=csv&gid=${source.gid}`;const response=await fetch(csvUrl);if(!response.ok)throw new Error(`Google Sheet returned HTTP ${response.status}`);const csv=await response.text();const nextHash=hash(csv);if(!force&&nextHash===source.lastHash){await LeadSource.updateOne({_id:source._id},{lastCheckedAt:new Date(),lastError:""});return{changed:false,added:0,updated:0,removed:0}}const rows=parseCsv(csv);if(!rows.length)return{changed:false,added:0,updated:0,removed:0};const headers=rows[0].map(h=>h.trim().toLowerCase());const phoneIdx=headers.findIndex(h=>/phone|mobile|number/.test(h));if(phoneIdx<0)throw new Error("No phone/mobile column found in this sheet");const nameIdx=headers.findIndex(h=>/^name$|full.?name/.test(h));const plotIdx=headers.findIndex(h=>/farukh|farrukh|plot/.test(h));const hintIdx=headers.findIndex(h=>/campaign|ad.?name|type/.test(h));const incoming=new Map<string,{phone:string;name:string;plot:string;category:string}>();for(const row of rows.slice(1)){const phone=normalizePhone(row[phoneIdx]||"");if(!phone||/test lead/i.test(row.join(" ")))continue;incoming.set(phone,{phone,name:clean(nameIdx>=0?row[nameIdx]:"",120),plot:clean(plotIdx>=0?row[plotIdx]:"",120),category:inferCategory(clean(hintIdx>=0?row[hintIdx]:""))})}const existing=await Lead.find({ownerId,phone:{$in:[...incoming.keys()]}}).lean();const byPhone=new Map(existing.map(l=>[l.phone,l]));let added=0,updated=0;for(const l of incoming.values()){const cur=byPhone.get(l.phone);if(!cur){await Lead.create({ownerId,...l,sourceIds:[source._id],sheetDate:new Date()});added++;continue}const set:any={archived:false};if(l.name&&l.name!==cur.name)set.name=l.name;if(!cur.plotManual&&l.plot&&l.plot!==cur.plotInFarukhNagar)set.plotInFarukhNagar=l.plot;if(!cur.category&&l.category)set.category=l.category;await Lead.updateOne({_id:cur._id},{$set:set,$addToSet:{sourceIds:source._id}});updated++}const ids=[...incoming.keys()];await Lead.updateMany({ownerId,sourceIds:source._id,phone:{$nin:ids}},{$pull:{sourceIds:source._id}});await Lead.updateMany({ownerId,sourceIds:{$size:0}},{$set:{archived:true}});await LeadSource.updateOne({_id:source._id},{lastHash:nextHash,lastSyncedAt:new Date(),lastCheckedAt:new Date(),lastError:""});return{changed:true,added,updated,removed:0}}
let timer:NodeJS.Timeout|undefined;export function startLeadSyncScheduler(intervalSeconds=15){if(timer)clearInterval(timer);const tick=async()=>{const sources=await LeadSource.find({enabled:true}).lean();for(const source of sources){try{await syncSource(source,String(source.ownerId))}catch(err){await LeadSource.updateOne({_id:source._id},{lastCheckedAt:new Date(),lastError:err instanceof Error?err.message:String(err)})}}};void tick();timer=setInterval(()=>void tick(),intervalSeconds*1000);timer.unref?.()}